# Generated by Django 4.1.3 on 2023-07-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_inscricoes_email_alter_inscricoes_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=300)),
                ('body', models.TextField(max_length=1200)),
            ],
        ),
    ]
